[options]
work_mode = "sys"
library = "GnomeDesktop"
version = "4.0"
min_cfg_version = "4.0"
single_version_file = "."
girs_directories = ["../../gir-files", "../../"]

external_libraries = [
    "GLib",
    "Gio",
]
