// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT(GNOME_DESKTOP_PLATFORM_VERSION);
    PRINT_CONSTANT((gint) GNOME_DESKTOP_THUMBNAIL_SIZE_LARGE);
    PRINT_CONSTANT((gint) GNOME_DESKTOP_THUMBNAIL_SIZE_NORMAL);
    PRINT_CONSTANT((gint) GNOME_DESKTOP_THUMBNAIL_SIZE_XLARGE);
    PRINT_CONSTANT((gint) GNOME_DESKTOP_THUMBNAIL_SIZE_XXLARGE);
    return 0;
}
