// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GnomeDesktopThumbnailFactory", sizeof(GnomeDesktopThumbnailFactory), alignof(GnomeDesktopThumbnailFactory));
    printf("%s;%zu;%zu\n", "GnomeDesktopThumbnailFactoryClass", sizeof(GnomeDesktopThumbnailFactoryClass), alignof(GnomeDesktopThumbnailFactoryClass));
    printf("%s;%zu;%zu\n", "GnomeDesktopThumbnailSize", sizeof(GnomeDesktopThumbnailSize), alignof(GnomeDesktopThumbnailSize));
    printf("%s;%zu;%zu\n", "GnomeIdleMonitor", sizeof(GnomeIdleMonitor), alignof(GnomeIdleMonitor));
    printf("%s;%zu;%zu\n", "GnomeIdleMonitorClass", sizeof(GnomeIdleMonitorClass), alignof(GnomeIdleMonitorClass));
    printf("%s;%zu;%zu\n", "GnomePnpIds", sizeof(GnomePnpIds), alignof(GnomePnpIds));
    printf("%s;%zu;%zu\n", "GnomePnpIdsClass", sizeof(GnomePnpIdsClass), alignof(GnomePnpIdsClass));
    printf("%s;%zu;%zu\n", "GnomeWallClock", sizeof(GnomeWallClock), alignof(GnomeWallClock));
    printf("%s;%zu;%zu\n", "GnomeWallClockClass", sizeof(GnomeWallClockClass), alignof(GnomeWallClockClass));
    printf("%s;%zu;%zu\n", "GnomeXkbInfo", sizeof(GnomeXkbInfo), alignof(GnomeXkbInfo));
    printf("%s;%zu;%zu\n", "GnomeXkbInfoClass", sizeof(GnomeXkbInfoClass), alignof(GnomeXkbInfoClass));
    return 0;
}
